### PR TITLE
Plugins examples with security content

### PR DESCRIPTION
**Pull request by skontar**
Some simple plugins for security checks

### CODE REVIEW

**Comment by skontar** [comment]
@PaulWay I have tried to update the rules. However, I am not able to test the changes, so I am a bit in the dark here.

**Comment by PaulWay** [comment]
OK, I did:
```bash
git checkout -b skontar-master
git pull https://github.com/skontar/insights-plugins-demo.git
py.test demo
```
and got:
```
demo/tests/integration.py:12: in pytest_generate_tests
    integration.generate_tests(metafunc, test_integration, "demo.tests", pattern=pattern)
../insights-core/insights/tests/integration.py:37: in generate_tests
    for t in ts:
../insights-core/insights/tests/__init__.py:91: in __wrap
    for input_data, expected in islice(func(), None, None, stride):
demo/tests/test_selinux_policy_mismatch.py:167: in integration_tests
    test_nonmatching_selinux()
demo/tests/test_selinux_policy_mismatch.py:111: in test_nonmatching_selinux
    assert 'policy_rpm' in response[0]
E   IndexError: list index out of range
```
Is that what you're getting?

**Comment by skontar** [comment]
@PaulWay I am still getting the same error message when trying to setup the environment. Can you please look into it?

**Comment by PaulWay** [comment]
Hi @skontar - sure, will look into this, one moment...

**Comment by PaulWay** [comment]
Hi @skontar - looks like the `crypography` library past version 2.0 is a bit touchy about Python 2.7.  Try:
```bash
pip install Sphinx==1.6.1
pip install cryptography==2.0
pip install -e insights-core[develop]
```
This throws up a bunch of compile warnings but everything installs and works correctly.

**Comment by skontar** [comment]
@PaulWay That worked. Please re-review.

**Pull request merged**
